# Generated by Django 5.2.14 on 2026-05-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('hr_officer', 'HR Officer'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20, unique=True)),
                ('enabled_widgets', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Customizations',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.CharField(choices=[('employee_overview', 'Employee Overview'), ('leave_overview', 'Leave Overview'), ('department_breakdown', 'Department Breakdown'), ('recent_activities', 'Recent Activities'), ('leave_type_distribution', 'Leave Type Distribution'), ('system_health', 'System Health'), ('on_leave_today', 'On Leave Today'), ('pending_approvals', 'Pending Approvals'), ('recent_applications', 'Recent Applications'), ('leave_balance_overview', 'Leave Balance Overview'), ('department_counts', 'Department Counts'), ('upcoming_holidays', 'Upcoming Holidays'), ('team_count', 'Team Count'), ('team_on_leave', 'Team On Leave'), ('approved_this_month', 'Approved This Month'), ('pending_requests', 'Pending Requests'), ('my_leave_balance', 'My Leave Balance'), ('quick_apply', 'Quick Apply'), ('calendar_mini', 'Calendar Mini')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fas fa-chart-bar', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('roles', models.JSONField(default=list)),
                ('default_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'ordering': ['widget_id'],
            },
        ),
    ]
